# Generated by Django 5.2.7 on 2025-10-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
    ]
