# Generated by Django 5.2.7 on 2025-10-19 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
