# Generated by Django 5.2.7 on 2025-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
