# Generated by Django 5.2.7 on 2025-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_delete_blog_remove_log_password_alter_log_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
