# Generated by Django 5.2.7 on 2025-10-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='email',
        ),
    ]
