# Generated by Django 5.2.7 on 2025-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_remove_log_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AddField(
            model_name='log',
            name='srno',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
