# Generated by Django 5.2.7 on 2025-10-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remove_log_id_log_srno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time',
            new_name='ryzen',
        ),
    ]
